### PR TITLE
bin: better missing nonce error

### PR DESCRIPTION
**Pull request by jacobhaven**
Addresses #21

### CODE REVIEW

**Comment by pinheadmz** [comment]
I think you forgot to commit this PR on a fresh branch :-) 
Your `Dockerfile` commit is still in there...

**Comment by jacobhaven** [comment]
Hah, the sin of comparing to `master` :)

Thanks @pinheadmz

**Comment by pinheadmz** [comment]
You don't have to close this, could probably fix with a rebase.

**Comment by jacobhaven** [comment]
@pinheadmz No, I have to change the source branch which GitHub doesn't allow.

**Pull request closed without merging**
